# Generated by Django 4.0.5 on 2022-10-20 03:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import shortage.apps.file_paths
import tinymce.models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=shortage.apps.file_paths.get_organization_path)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=shortage.apps.file_paths.get_organization_path)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('ein_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_draft', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('promote', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=100)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ein_number', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('category', models.CharField(choices=[('VITAL_GOODS', 'Vital Goods'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('BABY_CARE', 'Baby Care'), ('SAVE_ANIMALS', 'Save Animals')], db_index=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=shortage.apps.file_paths.get_product_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('requested_amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('top_priority', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.organization')),
            ],
        ),
    ]
