# Generated by Django 4.0.5 on 2022-06-30 03:40

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import shortage.apps.file_paths
import thumbnails.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('photo', thumbnails.fields.ImageField(blank=True, null=True, upload_to=shortage.apps.file_paths.get_organization_path)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.SmallIntegerField()),
                ('photo', thumbnails.fields.ImageField(blank=True, null=True, upload_to=shortage.apps.file_paths.get_product_path)),
                ('price', models.CharField(blank=True, max_length=32, null=True)),
                ('requested_amount', models.PositiveIntegerField(default=0)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('top_priority', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.organization')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='OnlineStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.organization')),
            ],
        ),
    ]
