# Generated by Django 4.0.5 on 2022-06-28 02:42

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import shortage.apps.catalog.models
import thumbnails.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('photo', thumbnails.fields.ImageField(blank=True, null=True, upload_to=shortage.apps.catalog.models.get_organization_path)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('delivery_company', models.CharField(max_length=100)),
                ('tracking_code', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('', 'Pending'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered')], default='', max_length=32, null=True)),
                ('photo', thumbnails.fields.ImageField(blank=True, null=True, upload_to=shortage.apps.catalog.models.get_package_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.SmallIntegerField()),
                ('photo', thumbnails.fields.ImageField(blank=True, null=True, upload_to=shortage.apps.catalog.models.get_product_path)),
                ('price', models.CharField(blank=True, max_length=32, null=True)),
                ('requested_amount', models.PositiveIntegerField(default=0)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('top_priority', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.organization')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.package')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.organization')),
            ],
        ),
    ]
