# Generated by Django 4.0.5 on 2022-07-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VITAL_GOODS', 'Vital Goods'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('BABY_CARE', 'Baby Care'), ('SAVE_ANIMALS', 'Save Animals')], max_length=255),
        ),
    ]
