# Generated by Django 4.0.5 on 2022-11-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_organizationregistrationrequest_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
