# Generated by Django 4.0.5 on 2022-07-24 20:29

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="country",
            field=django_countries.fields.CountryField(default="US", max_length=2),
        ),
    ]
