# Generated by Django 4.0.5 on 2022-11-14 20:09

from django.db import migrations
import shortage.apps.file_paths
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=thumbnails.fields.ImageField(upload_to=shortage.apps.file_paths.get_organization_path),
        ),
    ]
