# Generated by Django 4.0.5 on 2022-07-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("slug", "organization"), name="unique_slug_organization"
            ),
        ),
    ]
