# Generated by Django 4.0.5 on 2022-07-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_unique_slug_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
