# Generated by Django 4.0.5 on 2022-12-07 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortage.apps.file_paths
import thumbnails.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_organization_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationBlogPost',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=80)),
                ('content', tinymce.models.HTMLField()),
                ('meta_description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', thumbnails.fields.ImageField(blank=True, null=True, upload_to=shortage.apps.file_paths.get_blog_post_photo_path)),
                ('is_draft', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='catalog.organization')),
            ],
            options={
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
