# Generated by Django 4.0.5 on 2022-09-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tax_form_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
