# Generated by Django 4.0.5 on 2022-12-23 22:27

from django.db import migrations
import easy_thumbnails.fields
import shortage.apps.file_paths
import shortage.apps.storage


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_organizationblogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='banner',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_organization_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_organization_path),
        ),
        migrations.AlterField(
            model_name='organizationblogpost',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_blog_post_photo_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_product_path),
        ),
    ]
