# Generated by Django 4.0.5 on 2022-12-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_organization_banner_alter_organization_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationblogpost',
            name='promote',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
