# Generated by Django 4.0.5 on 2023-01-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_organizationblogpost_promote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VITAL_GOODS', 'Vital Goods'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('BABY_CARE', 'Baby Care'), ('SAVE_ANIMALS', 'Save Animals'), ('HOUSEHOLD_ITEMS', 'Household Items'), ('FOOD', 'Food'), ('TOYS', 'Toys'), ('HYGIENE', 'Hygiene')], db_index=True, max_length=255),
        ),
    ]
