# Generated by Django 4.0.5 on 2022-10-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_price_alter_product_requested_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='tax_form_url',
        ),
    ]
