# Generated by Django 4.0.5 on 2023-01-17 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationregistrationrequest',
            options={'permissions': (('can_receive_organization_registration_request_emails', 'Receive emails about organization registration request'),)},
        ),
    ]
