# Generated by Django 4.0.5 on 2022-10-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_organization_tax_form_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='photo',
            new_name='logo',
        ),
    ]
