# Generated by Django 4.0.5 on 2022-10-07 18:22

from django.db import migrations
import shortage.apps.file_paths
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_photo_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='banner',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to=shortage.apps.file_paths.get_organization_path),
        ),
    ]
