# Generated by Django 4.0.5 on 2023-01-19 17:48

from django.db import migrations, models
import easy_thumbnails.fields
import shortage.apps.file_paths
import shortage.apps.storage


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_organizationregistrationrequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_external_organization_path)),
                ('url', models.URLField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
