# Generated by Django 4.0.5 on 2023-01-26 17:56

from django.db import migrations, models
import shortage.apps.catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_externalorganization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, validators=[shortage.apps.catalog.models.validate_organization_slug_blacklist]),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VITAL_GOODS', 'Vital Goods'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('BABY_CARE', 'Baby Care'), ('SAVE_ANIMALS', 'Save Animals'), ('HOUSEHOLD_ITEMS', 'Household Items'), ('FOOD', 'Food'), ('TOYS', 'Toys'), ('HYGIENE', 'Hygiene'), ('CLOTHES', 'Clothes')], db_index=True, max_length=255),
        ),
    ]
