# Generated by Django 4.0.5 on 2023-01-21 12:59

from django.db import migrations, models
import shortage.apps.catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_externalorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('asin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=2000)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, validators=[shortage.apps.catalog.models.validate_organization_slug_blacklist]),
        ),
    ]
