# Generated by Django 4.0.5 on 2022-10-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_organizationregistrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='promote',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
