# Generated by Django 4.0.5 on 2023-01-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_organization_slug_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
