# Generated by Django 4.0.5 on 2023-02-02 17:31

from django.db import migrations, models
import easy_thumbnails.fields
import shortage.apps.catalog.models
import shortage.apps.file_paths
import shortage.apps.storage


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_organization_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'This address has already been taken.'}, max_length=80, unique=True, validators=[shortage.apps.catalog.models.validate_organization_slug_blacklist]),
        ),
    ]
