# Generated by Django 4.0.5 on 2023-02-09 19:23

from django.db import migrations, models
import django_countries.fields
import easy_thumbnails.fields
import phonenumber_field.modelfields
import shortage.apps.file_paths
import shortage.apps.storage


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_organization_logo_alter_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='representative_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='representative_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='representative_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='representative_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='organization',
            name='representative_signature',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_organization_path),
        ),
        migrations.AddField(
            model_name='organization',
            name='state_province_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
