# Generated by Django 4.0.5 on 2023-02-22 20:39

from django.db import migrations, models


def rename_save_animals_to_animal_care(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Product.objects.filter(category="SAVE_ANIMALS").update(category="ANIMAL_CARE")


def rename_animal_care_to_save_animals(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Product.objects.filter(category="ANIMAL_CARE").update(category="SAVE_ANIMALS")


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_organization_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("VITAL_GOODS", "Vital Goods"),
                    ("HEALTHCARE", "Healthcare"),
                    ("EDUCATION", "Education"),
                    ("BABY_CARE", "Baby Care"),
                    ("ANIMAL_CARE", "Animal Care"),
                    ("HOUSEHOLD_ITEMS", "Household Items"),
                    ("FOOD", "Food"),
                    ("TOYS", "Toys"),
                    ("HYGIENE", "Hygiene"),
                    ("CLOTHES", "Clothes"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.RunPython(
            rename_save_animals_to_animal_care,
            reverse_code=rename_animal_care_to_save_animals,
        ),
    ]
