# Generated by Django 4.0.5 on 2023-03-02 18:36

from django.db import migrations, models
import shortage.apps.catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ein_number',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[shortage.apps.catalog.models.validate_ein]),
        ),
    ]
