# Generated by Django 4.0.5 on 2023-03-03 00:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_organization_ein_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tax_deduction_receipt_footer',
            field=models.CharField(blank=True, help_text='Text added to automatically generated tax deduction receipts at the end of the document', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_deduction_receipt_preamble',
            field=models.CharField(blank=True, help_text='Text added to automatically generated tax deduction receipts before the table', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
