# Generated by Django 4.0.5 on 2023-03-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_organization_tax_deduction_receipt_footer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='tax_deduction_receipt_footer',
            new_name='tax_deduction_receipt_legal_information',
        ),
    ]
