# Generated by Django 4.0.5 on 2023-03-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_rename_tax_deduction_receipt_footer_organization_tax_deduction_receipt_legal_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('can_receive_organization_verification_request_emails', 'Receive organization verification request emails'),)},
        ),
    ]
