# Generated by Django 4.0.5 on 2023-03-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_organization_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mission_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='requested_goods',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
