# Generated by Django 4.0.5 on 2023-03-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_instruction_address_line1_instruction_address_line2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.AlterField(
            model_name='instruction',
            name='address_line1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='state_province_region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='zip',
            field=models.CharField(max_length=100),
        ),
    ]
