# Generated by Django 4.0.5 on 2023-03-10 00:08

from django.db import migrations
import easy_thumbnails.fields
import shortage.apps.file_paths
import shortage.apps.storage


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_remove_instruction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalorganization',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(max_length=500, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_external_organization_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='banner',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=500, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_organization_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='representative_signature',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=500, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_organization_path),
        ),
        migrations.AlterField(
            model_name='organizationblogpost',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=500, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_blog_post_photo_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=500, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_product_path),
        ),
    ]
