# Generated by Django 4.0.5 on 2023-03-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_externalorganization_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='representative_url',
            field=models.URLField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_deduction_receipt_legal_information',
            field=models.CharField(blank=True, help_text='Text added to automatically generated tax deduction receipts at the end of the document', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_deduction_receipt_preamble',
            field=models.CharField(blank=True, help_text='Text added to automatically generated tax deduction receipts before the table', max_length=1000, null=True),
        ),
    ]
