# Generated by Django 4.0.5 on 2023-08-29 01:23

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import shortage.apps.file_paths
import shortage.apps.storage
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_organization_representative_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('banner', easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=500, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_campaign_path)),
                ('requested_goods', models.CharField(blank=True, max_length=200, null=True)),
                ('mission_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_draft', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_slug_organization',
        ),
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('slug', 'organization'), name='unique_product_slug_organization'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='catalog.organization'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('slug', 'organization'), name='unique_campaign_slug_organization'),
        ),
    ]
