# Generated by Django 4.0.5 on 2023-08-30 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_campaign_remove_product_unique_slug_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='products',
            field=models.ManyToManyField(through='catalog.CampaignProduct', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.campaign'),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='campaignproduct',
            constraint=models.UniqueConstraint(fields=('campaign', 'product'), name='unique_campaign_product'),
        ),
    ]
