# Generated by Django 4.0.5 on 2024-03-21 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0033_rename_price_product_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationblogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
