# Generated by Django 4.0.5 on 2024-06-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_alter_organizationblogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='whitelabel',
            field=models.BooleanField(db_index=True, default=False, help_text='Does the organization use a custom page styling'),
        ),
    ]
