# Generated by Django 4.0.5 on 2024-09-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_alter_organizationblogpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('source', models.CharField(choices=[('GENERAL', 'General Demo'), ('SHOPIFY_INTEGRATION', 'Shopify Integration Demo')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('can_receive_demo_request_emails', 'Receive demo request emails'),),
            },
        ),
    ]
