# Generated by Django 4.0.5 on 2024-09-13 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_demorequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationRegistrationRequest',
        ),
    ]
