version: '3.4'

services:
  shortage-global-postgres:
    container_name: shortage-global-postgres
    image: "postgres:12.2"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"