version: '3.4'
services:
  shortage-global-nginx:
    container_name: shortage-global-nginx
    build:
      context: .
      dockerfile: Dockerfile
      target: static
    ports:
      - "80:80"
    links:
      - shortage-global-web

  shortage-global-web:
    container_name: shortage-global-web
    build:
      context: .
      dockerfile: Dockerfile
      target: application
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=${DATABASE_NAME:-postgres}
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - DATABASE_HOST=${DATABASE_HOST:-host.docker.internal}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,host.docker.internal,127.0.0.1}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-http://}
    command: bash -c "python manage.py migrate && gunicorn -w 8 shortage.wsgi --bind=0.0.0.0:8000 --access-logfile '-' --error-logfile '-'"
