"""
Django settings for shortage project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "tinymce",
    "django_countries",
    "auditlog",
    "storages",
    "rest_framework",
    "easy_thumbnails",
    "corsheaders",
    "shortage.apps.mailing",
    "shortage.apps.catalog",
    "shortage.apps.packages",
    "shortage.apps.users",
    "shortage.apps.blog",
    "phonenumber_field",
    "django_cleanup.apps.CleanupConfig",  # should be last
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
]

ROOT_URLCONF = "shortage.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "shortage/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "shortage.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT = BASE_DIR.joinpath("static")
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR.joinpath("media")
MEDIA_URL = "/media/"

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 15,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=15),
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

THUMBNAIL_ALIASES = {
    "": {
        "organization_logo_medium": {"size": (300, 300), "crop": False},
        "organization_banner_medium": {"size": (700, 700), "crop": False},
        "product_medium": {"size": (300, 300), "crop": False},
        "product_large": {"size": (1024, 1024), "crop": False},
        "package_medium": {"size": (1024, 1024), "crop": False},
        "blog_post_medium": {"size": (355, 200), "crop": True},
        "blog_post_large": {"size": (1244, 700), "crop": True},
        "card_preview": {"size": (533, 400), "crop": True},
    },
}

TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 500,
    "menubar": True,
    "plugins": "advlist,autolink,lists,link,image,charmap,print,preview,anchor,"
    "searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,paste,"
    "code,help,wordcount",
    "toolbar": " undo redo | formatselect | link | "
    "bold italic backcolor | alignleft aligncenter "
    "alignright alignjustify | bullist numlist outdent indent | "
    "removeformat | help",
    "relative_urls": False,
    "remove_script_host": False,
    "convert_urls": True,
    "images_upload_credentials": True,
    "images_upload_url": "/api/private/upload_image/",
    "images_upload_handler": "tinymceImageUploadHandler",  # included with extra media
}

# Include extra media to attach X-CSRFTOKEN header to image upload requests
# when uploading using django admin. Use correct /static/ url in production.
TINYMCE_EXTRA_MEDIA = {
    "js": ["{static_url}blog/tinymce_extra.js".format(static_url=STATIC_URL)],
}

# Since frontend serves nonprofit pages from the root, e.g. `https://shortage.global/[orgSlug]/...`,
# we should mark certain organization slugs as restricted to avoid collisions
ORGANIZATION_SLUG_BLACKLIST = [
    # automatically generated
    "robots.txt",
    "sitemap.xml",
    # /pages
    "account",
    "api",
    "donation",
    "private",
    "server-sitemap.xml",
    "for-corporate",
    "for-individuals",
    "for-nonprofits",
    "privacy-policy",
    "terms-of-use",
    # /public
    "images",
    "favicon.png",
    "manifest.json",
    # next.js
    "_next",
    "next",
    "build",
]

# IMPORTANT: the list of category keys must be synchronized with frontend
PRODUCT_CATEGORY = {
    "VITAL_GOODS": "VITAL_GOODS",
    "HEALTHCARE": "HEALTHCARE",
    "EDUCATION": "EDUCATION",
    "BABY_CARE": "BABY_CARE",
    "SAVE_ANIMALS": "SAVE_ANIMALS",
    "HOUSEHOLD_ITEMS": "HOUSEHOLD_ITEMS",
    "FOOD": "FOOD",
    "TOYS": "TOYS",
    "HYGIENE": "HYGIENE",
    "CLOTHES": "CLOTHES",
}

# IMPORTANT: the list of package statuses must be synchronized with frontend
PACKAGE_STATUS = {
    "REGISTERED": "REGISTERED",
    "PAYMENT_CANCELED": "PAYMENT_CANCELED",
    "PAYMENT_FAILED": "PAYMENT_FAILED",
    "PAYMENT_PROCESSING": "PAYMENT_PROCESSING",
    "PAYMENT_SUCCEEDED": "PAYMENT_SUCCEEDED",
    "CONFIRMED": "CONFIRMED",  # we received the payment (funded) or verified the tracking info (sent by donor)
    "ON_ITS_WAY": "ON_ITS_WAY",  # when payment is successful, we bought the goods and sent them
    "DELIVERED": "DELIVERED",
}

PACKAGE_TYPE = {
    "SENT_BY_DONOR": "SENT_BY_DONOR",
    "FUNDED_BY_DONOR": "FUNDED_BY_DONOR",
}

ADMIN_BASE_URL = os.getenv("DJANGO_ADMIN_BASE_URL", "")
FRONTEND_BASE_URL = os.getenv("DJANGO_FRONTEND_BASE_URL", "")

AUTH_USER_MODEL = "users.ShortageUser"

EMAIL_HOST = os.getenv("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = os.getenv("DJANGO_EMAIL_PORT", "")
EMAIL_HOST_USER = os.getenv("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("DJANGO_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("DJANGO_EMAIL_USE_TLS", "False") == "True"
EMAIL_USE_SSL = os.getenv("DJANGO_EMAIL_USE_SSL", "False") == "True"
SERVER_EMAIL = os.getenv("DJANGO_SERVER_EMAIL", "")

STRIPE_SECRET_KEY = os.getenv("DJANGO_STRIPE_SECRET_KEY", "")
STRIPE_ENDPOINT_SECRET = os.getenv("DJANGO_STRIPE_ENDPOINT_SECRET", "")
