# Generated by Django 4.0.5 on 2022-12-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='is_published',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
