# Generated by Django 4.0.5 on 2022-12-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_package_blog_posts_and_more'),
        ('blog', '0002_rename_is_published_blogpost_is_deleted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
