# Generated by Django 4.0.5 on 2024-03-21 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import shortage.apps.file_paths
import shortage.apps.storage
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortageBlogPost',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('content', tinymce.models.HTMLField()),
                ('meta_description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=500, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_blog_post_photo_path)),
                ('is_draft', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
