# Generated by Django 4.0.5 on 2022-10-20 03:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import shortage.apps.file_paths
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('need_tax_deduction', models.BooleanField(default=False)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province_region', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=100)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province_region', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('description', models.CharField(max_length=255)),
                ('quantity_description', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_pallets', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_value', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=shortage.apps.file_paths.get_corporate_donation_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('need_tax_deduction', models.BooleanField(default=False)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province_region', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('delivery_company', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('note', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('SENT_BY_DONOR', 'Sent by donor'), ('FUNDED_BY_DONOR', 'Funded by donor')], default='SENT_BY_DONOR', max_length=32)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PAYMENT_CANCELED', 'Payment Canceled'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('PAYMENT_SUCCEEDED', 'Payment Succeeded'), ('CONFIRMED', 'Confirmed'), ('ON_ITS_WAY', 'On Its Way'), ('DELIVERED', 'Delivered')], default='REGISTERED', max_length=32)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=shortage.apps.file_paths.get_package_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packages.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='catalog.product')),
            ],
        ),
    ]
