# Generated by Django 4.0.5 on 2022-11-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='agreed_to_terms_of_use',
            field=models.BooleanField(default=False),
        ),
    ]
