# Generated by Django 4.0.5 on 2022-07-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0002_alter_package_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("REGISTERED", "Registered"),
                    ("CONFIRMED", "Confirmed"),
                    ("DELIVERED", "Delivered"),
                ],
                default="REGISTERED",
                max_length=32,
            ),
        ),
    ]
