# Generated by Django 4.0.5 on 2022-07-29 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_is_deleted"),
        ("packages", "0003_alter_package_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageitem",
            name="package",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="package_items",
                to="packages.package",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="packageitem",
            name="product",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="package_items",
                to="catalog.product",
            ),
            preserve_default=False,
        ),
    ]
