# Generated by Django 4.0.5 on 2022-11-21 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_cart_agreed_to_terms_of_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageStatusLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PAYMENT_CANCELED', 'Payment Canceled'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('PAYMENT_SUCCEEDED', 'Payment Succeeded'), ('CONFIRMED', 'Confirmed'), ('ON_ITS_WAY', 'On Its Way'), ('DELIVERED', 'Delivered')], default='REGISTERED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_log', to='packages.package')),
            ],
        ),
    ]
