# Generated by Django 4.0.5 on 2022-11-23 16:29

import django.core.validators
from django.db import migrations, models
import shortage.apps.file_paths
import shortage.apps.storage


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_packagestatuslogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='tax_deduction_receipt',
            field=models.FileField(blank=True, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_tax_deduction_receipt_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
