# Generated by Django 4.0.5 on 2022-11-25 16:53

from django.db import migrations, models
import django.db.models.deletion
from shortage.apps.packages.models import Package


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_organization_logo"),
        ("packages", "0005_package_tax_deduction_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="catalog.organization",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="catalog.organization",
            ),
            preserve_default=False,
        ),
    ]
