# Generated by Django 4.0.5 on 2022-11-23 19:15
from django.db import migrations, models
import django.db.models.deletion

from shortage.apps.packages.models import PackageItem


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_organization_logo'),
        ('packages', '0005_package_tax_deduction_receipt'),
    ]

    def migrate_organization_from_product_to_package(apps, schema_editor):
        for package_item in PackageItem.objects.all():
            package = package_item.package
            package.organization = package_item.product.organization
            package.save()

    operations = [
        migrations.AddField(
            model_name='package',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='catalog.organization'),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_organization_from_product_to_package),
    ]
