# Generated by Django 4.0.5 on 2022-09-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_cart_alter_packageitem_package_cartitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_cart_product'),
        ),
    ]
