# Generated by Django 4.0.5 on 2022-12-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_is_published_blogpost_is_deleted_and_more'),
        ('packages', '0006_package_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='blog_posts',
            field=models.ManyToManyField(through='packages.PackageBlogPost', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='packageblogpost',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
        ),
        migrations.AlterUniqueTogether(
            name='packageblogpost',
            unique_together={('package', 'blog_post')},
        ),
    ]
