# Generated by Django 4.0.5 on 2022-09-19 23:50

from django.db import migrations, models
import django_countries.fields
import shortage.apps.file_paths
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_cartitem_unique_cart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province_region', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('description', models.CharField(max_length=255)),
                ('quantity_description', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_pallets', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_value', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('photo', thumbnails.fields.ImageField(blank=True, null=True, upload_to=shortage.apps.file_paths.get_corporate_donation_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
