# Generated by Django 4.0.5 on 2022-12-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_organizationblogpost'),
        ('packages', '0007_packageblogpost_package_blog_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='blog_posts',
            field=models.ManyToManyField(through='packages.PackageBlogPost', to='catalog.organizationblogpost'),
        ),
        migrations.AlterField(
            model_name='packageblogpost',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.organizationblogpost'),
        ),
    ]
