# Generated by Django 4.0.5 on 2022-12-22 22:46

from django.db import migrations
import easy_thumbnails.fields
import shortage.apps.file_paths
import shortage.apps.storage


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_package_blog_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_package_path),
        ),
    ]
