# Generated by Django 4.0.5 on 2022-12-23 22:27

from django.db import migrations
import easy_thumbnails.fields
import shortage.apps.file_paths
import shortage.apps.storage


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_alter_package_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatedonation',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_corporate_donation_path),
        ),
    ]
