# Generated by Django 4.0.5 on 2022-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_alter_cartitem_quantity_alter_packageitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='full_name',
        ),
        migrations.AddField(
            model_name='package',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
