# Generated by Django 4.0.5 on 2023-01-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_alter_corporatedonation_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'permissions': (('can_receive_package_registration_emails', 'Receive emails about package registration'),)},
        ),
    ]
