# Generated by Django 4.0.5 on 2022-09-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_cart_address_line1_cart_address_line2_cart_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
