# Generated by Django 4.0.5 on 2023-01-17 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_alter_package_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporatedonation',
            options={'permissions': (('can_receive_corporate_donation_emails', 'Receive emails about corporate donations'),)},
        ),
    ]
