# Generated by Django 4.0.5 on 2023-03-10 00:08

from django.db import migrations
import easy_thumbnails.fields
import shortage.apps.file_paths
import shortage.apps.storage


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_alter_corporatedonation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatedonation',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=500, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_corporate_donation_path),
        ),
        migrations.AlterField(
            model_name='package',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=500, null=True, storage=shortage.apps.storage.MediaStorage(), upload_to=shortage.apps.file_paths.get_package_path),
        ),
    ]
