# Generated by Django 4.0.5 on 2022-09-26 21:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_cartitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatedonation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
