# Generated by Django 4.0.5 on 2022-09-29 10:46

from django.db import migrations, models
from django.core.validators import URLValidator


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_alter_corporatedonation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='checkout_url',
            field=models.TextField(null=True, blank=True, validators=[URLValidator()]),
        ),
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('SENT_BY_DONOR', 'Sent by donor'), ('FUNDED_BY_DONOR', 'Funded by donor')], default='SENT_BY_DONOR', max_length=32),
        ),
        migrations.AlterField(
            model_name='package',
            name='delivery_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
