# Generated by Django 4.0.5 on 2023-03-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_alter_corporatedonation_photo_alter_package_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('DROPPED_OFF_BY_DONOR', 'Dropped off by donor'), ('SENT_BY_DONOR', 'Sent by donor'), ('FUNDED_BY_DONOR', 'Funded by donor')], default='SENT_BY_DONOR', max_length=32),
        ),
    ]
