# Generated by Django 4.0.5 on 2022-09-29 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_alter_corporatedonation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='checkout_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('SENT_BY_DONOR', 'Sent by donor'), ('FUNDED_BY_DONOR', 'Funded by donor')], default='SENT_BY_DONOR', max_length=32),
        ),
        migrations.AlterField(
            model_name='package',
            name='delivery_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('PAYMENT_FAILED', 'Payment failed'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('DELIVERED', 'Delivered')], default='REGISTERED', max_length=32),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
