# Generated by Django 4.0.5 on 2022-10-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_package_checkout_url_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('PAYMENT_CANCELED', 'Payment Canceled'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('PAYMENT_SUCCEEDED', 'Payment Succeeded'), ('CONFIRMED', 'Confirmed'), ('DELIVERED', 'Delivered')], default='REGISTERED', max_length=32),
        ),
    ]
