# Generated by Django 4.0.5 on 2023-08-29 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_campaign_remove_product_unique_slug_organization_and_more'),
        ('packages', '0014_alter_package_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.campaign'),
        ),
        migrations.AddField(
            model_name='package',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='catalog.campaign'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'campaign'), name='unique_cart_product'),
        ),
    ]
