# Generated by Django 4.0.5 on 2022-10-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_package_checkout_url_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('REGISTERED', 'Registered'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_FAILED', 'Payment failed'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('DELIVERED', 'Delivered')], default='CREATED', max_length=32),
        ),
    ]
