# Generated by Django 4.0.5 on 2024-01-03 05:03

import django.core.validators
from django.db import migrations, models
import easy_thumbnails.fields
import shortage.apps.file_paths
import shortage.apps.storage
import tinymce.models


def populate_product_details(apps, schema_editor):
    PackageItem = apps.get_model("packages", "PackageItem")
    package_items = PackageItem.objects.filter(price=None)

    for package_item in package_items:
        package_item.name = package_item.product.name
        package_item.category = package_item.product.category
        package_item.price = package_item.product.price
        package_item.description = package_item.product.description
        package_item.photo = package_item.product.photo
        package_item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0015_remove_cartitem_unique_cart_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageitem",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VITAL_GOODS", "Vital Goods"),
                    ("HEALTHCARE", "Healthcare"),
                    ("EDUCATION", "Education"),
                    ("BABY_CARE", "Baby Care"),
                    ("ANIMAL_CARE", "Animal Care"),
                    ("HOUSEHOLD_ITEMS", "Household Items"),
                    ("FOOD", "Food"),
                    ("TOYS", "Toys"),
                    ("HYGIENE", "Hygiene"),
                    ("CLOTHES", "Clothes"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="packageitem",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packageitem",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="packageitem",
            name="photo",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                max_length=500,
                null=True,
                storage=shortage.apps.storage.MediaStorage(),
                upload_to=shortage.apps.file_paths.get_package_item_path,
            ),
        ),
        migrations.AddField(
            model_name="packageitem",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.RunPython(
            populate_product_details,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
