# Generated by Django 4.0.5 on 2022-10-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_alter_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('PAYMENT_CANCELED', 'Payment Canceled'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('PAYMENT_SUCCEEDED', 'Payment Succeeded'), ('CONFIRMED', 'Confirmed'), ('ON_ITS_WAY', 'On Its Way'), ('DELIVERED', 'Delivered')], default='REGISTERED', max_length=32),
        ),
    ]
