# Generated by Django 4.0.5 on 2024-05-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_packageitem_category_packageitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('DROPPED_OFF_BY_DONOR', 'Dropped off by donor'), ('SENT_BY_DONOR', 'Sent by donor'), ('FUNDED_BY_DONOR', 'Funded by donor'), ('SHOPIFY_PURCHASE', 'Purchased on Shopify')], default='SENT_BY_DONOR', max_length=32),
        ),
    ]
