# Generated by Django 4.0.5 on 2024-07-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_alter_organizationblogpost_author'),
        ('packages', '0017_alter_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='shopify_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('organization', 'shopify_order_id')},
        ),
    ]
