RAINFOREST_SAMPLE_RESPONSE = {
    "request_info": {
        "success": True,
        "credits_used": 2,
        "credits_remaining": 98,
        "credits_used_this_request": 1,
    },
    "request_parameters": {
        "type": "product",
        "amazon_domain": "amazon.com",
        "asin": "B000YDDF6O",
    },
    "request_metadata": {
        "created_at": "2023-01-20T19:24:17.334Z",
        "processed_at": "2023-01-20T19:24:40.903Z",
        "total_time_taken": 23.57,
        "amazon_url": "https://www.amazon.com/dp/B000YDDF6O?th=1&psc=1",
    },
    "product": {
        "title": "Baby Einstein Take Along Tunes Musical Toy, Ages 3 months +",
        "search_alias": {"title": "Baby", "value": "baby-products"},
        "keywords": "Baby,Einstein,Take,Along,Tunes,Musical,Toy,,Ages,3,months,+",
        "keywords_list": [
            "Baby",
            "Einstein",
            "Take",
            "Along",
            "Tunes",
            "Musical",
            "Ages",
            "months",
        ],
        "asin": "B000YDDF6O",
        "parent_asin": "B094N3QBWX",
        "link": "https://www.amazon.com/Baby-Einstein-Along-Tunes-Musical/dp/B000YDDF6O",
        "brand": "Baby Einstein",
        "sell_on_amazon": True,
        "bestseller_badge": {
            "link": "https://www.amazon.com/gp/bestsellers/toys-and-games/196607011/ref=zg_b_bs_196607011_1",
            "category": "Baby Musical Toys",
            "badge_text": "#1 Best Seller",
        },
        "variants": [
            {
                "asin": "B000YDDF6O",
                "title": "Take Along Tunes",
                "is_current_product": True,
                "link": "https://www.amazon.com/dp/B000YDDF6O?th=1&psc=1",
                "dimensions": [{"name": "Style", "value": "Take Along Tunes"}],
                "main_image": "https://m.media-amazon.com/images/I/81s+p-98uyL._SL1500_.jpg",
                "images": [
                    {
                        "variant": "MAIN",
                        "link": "https://m.media-amazon.com/images/I/81s+p-98uyL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT01",
                        "link": "https://m.media-amazon.com/images/I/91oJ42AIvNL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT02",
                        "link": "https://m.media-amazon.com/images/I/91MQyqmopwL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT03",
                        "link": "https://m.media-amazon.com/images/I/8111iK0kvEL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT04",
                        "link": "https://m.media-amazon.com/images/I/912uL+NLD7L._SL1500_.jpg",
                    },
                    {
                        "variant": "PT05",
                        "link": "https://m.media-amazon.com/images/I/910EyRw4aTL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT06",
                        "link": "https://m.media-amazon.com/images/I/91PRLvMCwCL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT07",
                        "link": "https://m.media-amazon.com/images/I/81G0plbFMJL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT08",
                        "link": "https://m.media-amazon.com/images/I/91DgSDVR4AL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT09",
                        "link": "https://m.media-amazon.com/images/I/91ZoEhK8X0L._SL1500_.jpg",
                    },
                    {
                        "variant": "PT10",
                        "link": "https://m.media-amazon.com/images/I/71nlK9-PYGL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT11",
                        "link": "https://m.media-amazon.com/images/I/91SnE+rDurL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT12",
                        "link": "https://m.media-amazon.com/images/I/819sIJh-voL._SL1500_.jpg",
                    },
                    {
                        "variant": "AW01",
                        "link": "https://m.media-amazon.com/images/I/51IDtCCF5-L.jpg",
                    },
                ],
            },
            {
                "asin": "B092DV3RZY",
                "title": "Developmental Toy Kit",
                "is_current_product": False,
                "link": "https://www.amazon.com/dp/B092DV3RZY?th=1&psc=1",
                "dimensions": [{"name": "Style", "value": "Developmental Toy Kit"}],
                "main_image": "https://m.media-amazon.com/images/I/81AEnsRU4LL._SL1500_.jpg",
                "images": [
                    {
                        "variant": "MAIN",
                        "link": "https://m.media-amazon.com/images/I/81AEnsRU4LL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT01",
                        "link": "https://m.media-amazon.com/images/I/71WIbKf3TlL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT02",
                        "link": "https://m.media-amazon.com/images/I/81fkZsoF+mL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT03",
                        "link": "https://m.media-amazon.com/images/I/91OJ7N9WaLL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT04",
                        "link": "https://m.media-amazon.com/images/I/81NS6aA9ogL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT05",
                        "link": "https://m.media-amazon.com/images/I/81IWbstTBWL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT06",
                        "link": "https://m.media-amazon.com/images/I/91ZW4ZMAeuL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT07",
                        "link": "https://m.media-amazon.com/images/I/61mBcciPXdL._SL1500_.jpg",
                    },
                    {
                        "variant": "PT08",
                        "link": "https://m.media-amazon.com/images/I/71BxzpbKz8L._SL1500_.jpg",
                    },
                ],
            },
        ],
        "variant_asins_flat": "B000YDDF6O,B092DV3RZY",
        "categories": [
            {"name": "Baby"},
            {
                "name": "Toys & Games",
                "link": "https://www.amazon.com/toys/b/ref=dp_bc_aui_C_1?ie=UTF8&node=165793011",
                "category_id": "165793011",
            },
            {
                "name": "Baby & Toddler Toys",
                "link": "https://www.amazon.com/Baby-Toys-Preschool/b/ref=dp_bc_aui_C_2?ie=UTF8&node=196601011",
                "category_id": "196601011",
            },
            {
                "name": "Musical Toys",
                "link": "https://www.amazon.com/Baby-Musical-Toys/b/ref=dp_bc_aui_C_3?ie=UTF8&node=196607011",
                "category_id": "196607011",
            },
        ],
        "categories_flat": "Baby > Toys & Games > Baby & Toddler Toys > Musical Toys",
        "description": "PRODUCT DESCRIPTION \n Baby Einstein take along tunes. \n\n FROM THE MANUFACTURER \n Promote music appreciation and auditory development by introducing your little one to baby-friendly versions of classical masterpieces by Mozart, Vivaldi, Chopin and Rossini with the Baby Einstein take along Tunes. A large, easy to press button allows your baby to toggle through 7 high quality and enjoyable classical melodies at home, or for on-the-go fun. This baby's version of an MP3 player has colorful lights that dance across the screen to enhance each entertaining melody and promote visual perception.",
        "promotions_feature": "Buy at least 4 items of your choice and save 5%. Discount by Amazon.",
        "a_plus_content": {
            "has_a_plus_content": True,
            "has_brand_story": True,
            "brand_story": {
                "hero_image": "https://m.media-amazon.com/images/S/aplus-media-library-service-media/f1996e32-6434-4256-8a51-ea3e25c37376.__CR0,0,1464,625_PT0_SX1464_V1___.png",
                "brand_store": {
                    "link": "/stores/page/53A71350-31C3-4D12-980C-58FB8A9ED2E6",
                    "id": "53A71350-31C3-4D12-980C-58FB8A9ED2E6",
                },
                "images": [
                    "https://m.media-amazon.com/images/S/aplus-media-library-service-media/f1996e32-6434-4256-8a51-ea3e25c37376.__CR0,0,1464,625_PT0_SX1464_V1___.png"
                ],
                "products": [
                    {
                        "title": "Baby Einstein Flip For Art High Contrast Floor Activity Mirror with Take Along Cards, Tummy Time ...",
                        "asin": "B07N7HFJKF",
                        "link": "/dp/B07N7HFJKF/ref=emc_bcc_2_i",
                        "image": "https://m.media-amazon.com/images/I/41ckSrZPkHL.__AC_SR166,182___.jpg",
                    },
                    {
                        "title": "Baby Einstein Bendy Ball Rattle Toy, Ages 3 months +",
                        "asin": "B001UF8BL4",
                        "link": "/dp/B001UF8BL4/ref=emc_bcc_2_i",
                        "image": "https://m.media-amazon.com/images/I/41IKEQLaNHL.__AC_SR166,182___.jpg",
                    },
                    {
                        "title": "Baby Einstein Glow & Discover Light Bar Activity Station",
                        "asin": "B06Y1192MF",
                        "link": "/dp/B06Y1192MF/ref=emc_bcc_2_i",
                        "image": "https://m.media-amazon.com/images/I/41b-8iBN3XL.__AC_SR166,182___.jpg",
                    },
                    {
                        "title": "Baby Einstein Teether-pillar Rattle and Chill Teething Toy, Ages 3 months +",
                        "asin": "B01CVDU1C0",
                        "link": "/dp/B01CVDU1C0/ref=emc_bcc_2_i",
                        "image": "https://m.media-amazon.com/images/I/417IvwzjKwL.__AC_SR166,182___.jpg",
                    },
                    {
                        "title": 'Baby Einstein Octoplush Musical Octopus Stuffed Animal Plush Toy, Age 3 Month+, Blue, 11"',
                        "asin": "B000TFLAZA",
                        "link": "/dp/B000TFLAZA/ref=emc_bcc_2_i",
                        "image": "https://m.media-amazon.com/images/I/41y-oQPixzS.__AC_SR166,182___.jpg",
                    },
                    {
                        "title": "Baby Einstein Zen The Zebra Sensory Plush Teether Toy, Ages Newborn +",
                        "asin": "B08TRPJMQ4",
                        "link": "/dp/B08TRPJMQ4/ref=emc_bcc_2_i",
                        "image": "https://m.media-amazon.com/images/I/419PpVs5-xL.__AC_SR166,182___.jpg",
                    },
                    {
                        "title": "Baby Einstein Star Bright Symphony Plush Musical Take-Along Toy, Ages Newborn + (Pack of 1)",
                        "asin": "B00TFAOIY0",
                        "link": "/dp/B00TFAOIY0/ref=emc_bcc_2_i",
                        "image": "https://m.media-amazon.com/images/I/41d5EX2YYgL.__AC_SR166,182___.jpg",
                    },
                    {
                        "title": "Baby Einstein Curious Explorers Teether Book Take-Along Toy, Ages Newborn +",
                        "asin": "B07NDD2YBQ",
                        "link": "/dp/B07NDD2YBQ/ref=emc_bcc_2_i",
                        "image": "https://m.media-amazon.com/images/I/51p-mrtgFaL.__AC_SR166,182___.jpg",
                    },
                    {
                        "title": "Baby Einstein Sea Dreams Soother Musical Crib Toy and Sound Machine, Newborns Plus",
                        "asin": "B07DM86Z43",
                        "link": "/dp/B07DM86Z43/ref=emc_bcc_2_i",
                        "image": "https://m.media-amazon.com/images/I/41SO4Hga7cL.__AC_SR166,182___.jpg",
                    },
                    {
                        "title": "Baby Einstein Discovering Music Activity Table, Ages 6 months +",
                        "asin": "B005P5D7G4",
                        "link": "/dp/B005P5D7G4/ref=emc_bcc_2_i",
                        "image": "https://m.media-amazon.com/images/I/41FX-0v7V8L.__AC_SR166,182___.jpg",
                    },
                    {
                        "title": "Baby Einstein Toddler Jams Musical Toy, 12 months Plus",
                        "asin": "B07QZSF1GK",
                        "link": "/dp/B07QZSF1GK/ref=emc_bcc_2_i",
                        "image": "https://m.media-amazon.com/images/I/41mZKrlUrtL.__AC_SR166,182___.jpg",
                    },
                    {
                        "title": "Baby Einstein Rock, Light & Roll Guitar Musical Toy, Ages 3 Months +",
                        "asin": "B00ZIYFU80",
                        "link": "/dp/B00ZIYFU80/ref=emc_bcc_2_i",
                        "image": "https://m.media-amazon.com/images/I/41QhenzVcFL.__AC_SR166,182___.jpg",
                    },
                ],
            },
            "third_party": False,
        },
        "sub_title": {
            "text": "Visit the Baby Einstein Store",
            "link": "https://www.amazon.com/stores/BabyEinstein/page/E1E1E35C-3C06-4F59-A626-D50E3F999C85?ref_=ast_bln",
        },
        "has_coupon": True,
        "coupon_text": "Save 5% on 4 select item(s). Discount by Amazon.",
        "rating": 4.8,
        "rating_breakdown": {
            "five_star": {"percentage": 86, "count": 42911},
            "four_star": {"percentage": 9, "count": 4490},
            "three_star": {"percentage": 3, "count": 1496},
            "two_star": {"percentage": 1, "count": 498},
            "one_star": {"percentage": 1, "count": 498},
        },
        "ratings_total": 49897,
        "main_image": {"link": "https://m.media-amazon.com/images/I/81s+p-98uyL.jpg"},
        "images": [
            {
                "link": "https://m.media-amazon.com/images/I/81s+p-98uyL._SL1500_.jpg",
                "variant": "MAIN",
            },
            {
                "link": "https://m.media-amazon.com/images/I/91oJ42AIvNL._SL1500_.jpg",
                "variant": "PT01",
            },
            {
                "link": "https://m.media-amazon.com/images/I/91MQyqmopwL._SL1500_.jpg",
                "variant": "PT02",
            },
            {
                "link": "https://m.media-amazon.com/images/I/8111iK0kvEL._SL1500_.jpg",
                "variant": "PT03",
            },
            {
                "link": "https://m.media-amazon.com/images/I/912uL+NLD7L._SL1500_.jpg",
                "variant": "PT04",
            },
            {
                "link": "https://m.media-amazon.com/images/I/910EyRw4aTL._SL1500_.jpg",
                "variant": "PT05",
            },
            {
                "link": "https://m.media-amazon.com/images/I/91PRLvMCwCL._SL1500_.jpg",
                "variant": "PT06",
            },
            {
                "link": "https://m.media-amazon.com/images/I/81G0plbFMJL._SL1500_.jpg",
                "variant": "PT07",
            },
            {
                "link": "https://m.media-amazon.com/images/I/91DgSDVR4AL._SL1500_.jpg",
                "variant": "PT08",
            },
            {
                "link": "https://m.media-amazon.com/images/I/91ZoEhK8X0L._SL1500_.jpg",
                "variant": "PT09",
            },
            {
                "link": "https://m.media-amazon.com/images/I/71nlK9-PYGL._SL1500_.jpg",
                "variant": "PT10",
            },
            {
                "link": "https://m.media-amazon.com/images/I/91SnE+rDurL._SL1500_.jpg",
                "variant": "PT11",
            },
            {
                "link": "https://m.media-amazon.com/images/I/819sIJh-voL._SL1500_.jpg",
                "variant": "PT12",
            },
            {
                "link": "https://m.media-amazon.com/images/I/51IDtCCF5-L.jpg",
                "variant": "AW01",
            },
        ],
        "images_count": 14,
        "images_flat": "https://m.media-amazon.com/images/I/81s+p-98uyL._SL1500_.jpg,https://m.media-amazon.com/images/I/91oJ42AIvNL._SL1500_.jpg,https://m.media-amazon.com/images/I/91MQyqmopwL._SL1500_.jpg,https://m.media-amazon.com/images/I/8111iK0kvEL._SL1500_.jpg,https://m.media-amazon.com/images/I/912uL+NLD7L._SL1500_.jpg,https://m.media-amazon.com/images/I/910EyRw4aTL._SL1500_.jpg,https://m.media-amazon.com/images/I/91PRLvMCwCL._SL1500_.jpg,https://m.media-amazon.com/images/I/81G0plbFMJL._SL1500_.jpg,https://m.media-amazon.com/images/I/91DgSDVR4AL._SL1500_.jpg,https://m.media-amazon.com/images/I/91ZoEhK8X0L._SL1500_.jpg,https://m.media-amazon.com/images/I/71nlK9-PYGL._SL1500_.jpg,https://m.media-amazon.com/images/I/91SnE+rDurL._SL1500_.jpg,https://m.media-amazon.com/images/I/819sIJh-voL._SL1500_.jpg,https://m.media-amazon.com/images/I/51IDtCCF5-L.jpg",
        "videos": [
            {
                "duration_seconds": 27,
                "width": 854,
                "height": 480,
                "link": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/d0117083-b9c3-492b-ba79-8beb26df96b7/default.jobtemplate.mp4.480.mp4",
                "thumbnail": "https://m.media-amazon.com/images/I/81Ns4rkLTlL.SX522_.jpg",
                "is_hero_video": False,
                "variant": "MAIN",
                "group_id": "IB_G1",
                "group_type": "videos_for_this_product",
                "title": "Take Along Tunes Musical Toy",
            },
            {
                "duration_seconds": 40,
                "width": 854,
                "height": 480,
                "link": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/237bbf74-9df2-4d7d-bd99-ac03d7dd5bc3/default.jobtemplate.mp4.480.mp4",
                "thumbnail": "https://m.media-amazon.com/images/I/51GqvYcOCJL.SX522_.jpg",
                "is_hero_video": False,
                "variant": "MAIN",
                "group_id": "IB_G1",
                "group_type": "videos_for_this_product",
                "title": "Baby Einstein Brand Story",
            },
            {
                "duration_seconds": 19,
                "width": 720,
                "height": 404,
                "link": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/v2/d66f3035-72a9-5221-86e2-ae6f6a6e9c40/ShortForm-Generic-480p-16-9-1409173089793-rpcbe5.mp4",
                "thumbnail": "https://m.media-amazon.com/images/I/51S9AU53R6L.SX522_.jpg",
                "is_hero_video": False,
                "variant": "MAIN",
                "group_id": "IB_G1",
                "group_type": "videos_for_this_product",
                "title": "Baby Einstein Take Along Tunes Musical Toy",
            },
            {
                "duration_seconds": 47,
                "width": 854,
                "height": 480,
                "link": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/b2fb1cb7-5316-4a27-b98f-82dc5bd5f292/default.jobtemplate.mp4.480.mp4",
                "thumbnail": "https://m.media-amazon.com/images/I/C1BIDe5IoHL.SX522_.png",
                "is_hero_video": False,
                "variant": "MAIN",
                "group_id": "IB_G2_T1",
                "title": "Baby Einstein Take Along Tunes Review",
            },
            {
                "duration_seconds": 52,
                "width": 854,
                "height": 480,
                "link": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/091adb37-c1d3-4b9b-88d5-df4ba6dc5e35/default.jobtemplate.mp4.480.mp4",
                "thumbnail": "https://m.media-amazon.com/images/I/51-9sEgnMCL.SX522_.jpg",
                "is_hero_video": False,
                "variant": "MAIN",
                "group_id": "IB_G2_T1",
                "title": "MomTV Partner Feature: Baby Einstein - Take Long Tunes",
            },
            {
                "duration_seconds": 74,
                "width": 854,
                "height": 480,
                "link": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/251481da-da65-4515-bcdb-912f2f2e5b29/default.jobtemplate.mp4.480.mp4",
                "thumbnail": "https://m.media-amazon.com/images/I/A1tuGHwWy3L.SX522_.png",
                "is_hero_video": False,
                "variant": "MAIN",
                "group_id": "IB_G2_T1",
                "title": "Our Point of View on Baby Einstein Musical Toys",
            },
        ],
        "videos_count": 6,
        "videos_flat": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/d0117083-b9c3-492b-ba79-8beb26df96b7/default.jobtemplate.mp4.480.mp4,https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/237bbf74-9df2-4d7d-bd99-ac03d7dd5bc3/default.jobtemplate.mp4.480.mp4,https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/v2/d66f3035-72a9-5221-86e2-ae6f6a6e9c40/ShortForm-Generic-480p-16-9-1409173089793-rpcbe5.mp4,https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/b2fb1cb7-5316-4a27-b98f-82dc5bd5f292/default.jobtemplate.mp4.480.mp4,https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/091adb37-c1d3-4b9b-88d5-df4ba6dc5e35/default.jobtemplate.mp4.480.mp4,https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/251481da-da65-4515-bcdb-912f2f2e5b29/default.jobtemplate.mp4.480.mp4",
        "videos_additional": [
            {
                "id": "amzn1.vse.video.1ff8104512b2419082ce7bc1f565641f",
                "product_asin": "B000YDDF6O",
                "parent_asin": "B094N3QBWX",
                "related_products": "B000YDDF6O",
                "sponsor_products": "True",
                "title": "Baby Einstein Take Along Tunes Musical Toy",
                "profile_image_url": "https://www.amazon.com/avatar/default/amzn1.account.AGUKAZKUMHWYF43MYT2LVSNALYPQ?max_width=110&square=True",
                "profile_link": "/gp/profile/amzn1.account.AGUKAZKUMHWYF43MYT2LVSNALYPQ",
                "public_name": "Liz",
                "creator_type": "Customer",
                "vendor_code": "UGCPR",
                "vendor_name": "Liz",
                "video_image_id": "41PGzkCCEJL",
                "video_image_url": "https://m.media-amazon.com/images/I/41PGzkCCEJL._CR0,0,360,203_SR342,193_.jpg",
                "video_image_url_unchanged": "https://m.media-amazon.com/images/I/41PGzkCCEJL.jpg",
                "video_image_width": "360",
                "video_image_height": "480",
                "video_image_extension": "jpg",
                "video_url": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/c09b64ad-d0ce-4757-8580-5223f07b2d59/default.jobtemplate.hls.m3u8",
                "video_previews": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/d77d8b70-300e-4bda-9884-8439034b1d44/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
                "video_mime_type": "application/x-mpegURL",
                "duration": "0:36",
                "closed_captions": "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/f277d18d-17b4-4896-8793-db3d4ff569b9.vtt",
                "type": "videos_for_this_product",
            },
            {
                "id": "amzn1.vse.video.efb38d7a8c73498facc3523f71d33166",
                "product_asin": "B000YDDF6O",
                "parent_asin": "B094N3QBWX",
                "related_products": "B000YDDF6O",
                "sponsor_products": "True",
                "title": "Great first music toy",
                "profile_image_url": "https://www.amazon.com/avatar/default/amzn1.account.AHNRXJM2GJOJ6B3TVZRJRCXVG3PA?max_width=110&square=True",
                "profile_link": "/gp/profile/amzn1.account.AHNRXJM2GJOJ6B3TVZRJRCXVG3PA",
                "public_name": "GPRGRL",
                "creator_type": "Customer",
                "vendor_code": "AOD60",
                "vendor_name": "GPRGRL",
                "video_image_id": "51zoCAx1UEL",
                "video_image_url": "https://m.media-amazon.com/images/I/51zoCAx1UEL._CR2,0,1276,720_SR684,386_.jpg",
                "video_image_url_unchanged": "https://m.media-amazon.com/images/I/51zoCAx1UEL.jpg",
                "video_image_width": "1280",
                "video_image_height": "720",
                "video_image_extension": "jpg",
                "video_url": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/4332e691-93ae-4e1f-be79-cfe396552b9d/default.jobtemplate.hls.m3u8",
                "video_previews": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/00fec9d8-4160-4109-8fba-86b9ed1a99c7/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
                "video_mime_type": "application/x-mpegURL",
                "duration": "0:27",
                "type": "videos_for_this_product",
            },
            {
                "id": "amzn1.vse.video.b524b37ced3a46ec9688d729ccff0316",
                "product_asin": "B000YDDF6O",
                "parent_asin": "B094N3QBWX",
                "related_products": "B000YDDF6O",
                "sponsor_products": "True",
                "title": "Buy 2, 1 for back up!",
                "profile_image_url": "https://www.amazon.com/avatar/default/amzn1.account.AHIOE6L2MTXBT4ALOTI4PAD72HQQ?max_width=110&square=True",
                "profile_link": "/gp/profile/amzn1.account.AHIOE6L2MTXBT4ALOTI4PAD72HQQ",
                "public_name": "Umut D.",
                "creator_type": "Customer",
                "vendor_code": "AOD60",
                "vendor_name": "Umut D.",
                "video_image_id": "B19VSN5BhBS",
                "video_image_url": "https://m.media-amazon.com/images/I/B19VSN5BhBS._CR3,0,1914,1080_SR684,386_.png",
                "video_image_url_unchanged": "https://images-na.ssl-images-amazon.com/images/I/B19VSN5BhBS.png",
                "video_image_width": "1920",
                "video_image_height": "1080",
                "video_image_extension": "png",
                "video_url": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/v2/b60f1641-e2b2-5cfb-be4c-b4b857645d09/ShortForm-Generic-480p-16-9-1409173089793-rpcbe5.mp4",
                "video_previews": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/d79d51f2-265f-4c67-a2e0-b37f70ece87b/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
                "video_mime_type": "video/mp4",
                "duration": "4:56",
                "closed_captions": "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/8dd3e6d4-bb8b-4fe9-bb96-5aa3f2dc53f9.vtt",
                "type": "videos_for_this_product",
            },
            {
                "id": "amzn1.vse.video.c350664195c24cf58ef3daaa4841b9e5",
                "product_asin": "B000YDDF6O",
                "parent_asin": "B094N3QBWX",
                "related_products": "B000YDDF6O",
                "sponsor_products": "True",
                "title": "What would I do without it? Perfect for our long walks. People pay attention to music too, it's so ",
                "profile_image_url": "https://www.amazon.com/avatar/default/amzn1.account.AEF5K4QQ5MCI3E52EQNVFQEWSI4Q?max_width=110&square=True",
                "profile_link": "/gp/profile/amzn1.account.AEF5K4QQ5MCI3E52EQNVFQEWSI4Q",
                "public_name": "ladygoodmood",
                "creator_type": "Customer",
                "vendor_code": "AOD60",
                "vendor_name": "ladygoodmood",
                "video_image_id": "B1YkSqN3qmS",
                "video_image_url": "https://m.media-amazon.com/images/I/B1YkSqN3qmS._CR3,0,1914,1080_SR684,386_.png",
                "video_image_url_unchanged": "https://images-na.ssl-images-amazon.com/images/I/B1YkSqN3qmS.png",
                "video_image_width": "1920",
                "video_image_height": "1080",
                "video_image_extension": "png",
                "video_url": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/v2/4a52affc-60d6-5ca9-9ba7-231999dd6773/ShortForm-Generic-480p-16-9-1409173089793-rpcbe5.mp4",
                "video_previews": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/5516c63c-a193-466f-b8cd-a2e92c606a94/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
                "video_mime_type": "video/mp4",
                "duration": "3:30",
                "type": "videos_for_this_product",
            },
            {
                "id": "amzn1.vse.video.e4725fe63d034dd0aa341136e5d7fd67",
                "product_asin": "B000YDDF6O",
                "parent_asin": "B094N3QBWX",
                "related_products": "B000YDDF6O",
                "sponsor_products": "True",
                "title": "MomTv Partner Feature: Baby Einstein / Take Along Tunes",
                "profile_image_url": "https://www.amazon.com/avatar/default/amzn1.account.AFIRLYLENZUK2VH4EYMQXEH4E3IQ?max_width=110&square=True",
                "profile_link": "/gp/profile/amzn1.account.AFIRLYLENZUK2VH4EYMQXEH4E3IQ",
                "public_name": "MomSelect",
                "creator_type": "3P",
                "vendor_code": "A8E80NZUUJ8I8",
                "vendor_name": "MomSelect",
                "vendor_tracking_id": "bsmmedia-20",
                "video_image_id": "51JMkxmBHpL",
                "video_image_url": "https://m.media-amazon.com/images/I/51JMkxmBHpL._CR1,0,638,360_SR342,193_.jpg",
                "video_image_url_unchanged": "https://m.media-amazon.com/images/I/51JMkxmBHpL.jpg",
                "video_image_width": "640",
                "video_image_height": "360",
                "video_image_extension": "jpg",
                "video_url": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/fe27d590-532f-41ac-a875-7c59876b139f/default.jobtemplate.hls.m3u8",
                "video_previews": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/b7c58b3d-3bec-4e91-82f7-e9b6dbf4f421/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
                "video_mime_type": "application/x-mpegURL",
                "duration": "0:36",
                "closed_captions": "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/18f9513f-1210-485f-b2dd-3182a426cc23.vtt",
                "type": "videos_for_this_product",
            },
            {
                "id": "amzn1.vse.video.0aab889291e34e00a6e5f9a8d84a37f1",
                "product_asin": "B000YDDF6O",
                "parent_asin": "B094N3QBWX",
                "related_products": "B000YDDF6O",
                "sponsor_products": "True",
                "title": "Baby Einstein Take Along Tunes Review",
                "profile_image_url": "https://images-na.ssl-images-amazon.com/images/S/influencer-profile-image-prod/logo/collinmichael_1658437711496_original._CR462,0,1080,1080_._FMjpg_.jpeg",
                "profile_link": "/shop/collinmichael",
                "public_name": "CollinMichael96",
                "creator_type": "Influencer",
                "vendor_code": "collinmichael:shop",
                "vendor_name": "CollinMichael96",
                "vendor_tracking_id": "onamzcollinmi-20",
                "video_image_id": "C1BIDe5IoHL",
                "video_image_url": "https://m.media-amazon.com/images/I/C1BIDe5IoHL._CR3,0,1914,1080_SR684,386_.png",
                "video_image_url_unchanged": "https://m.media-amazon.com/images/I/C1BIDe5IoHL.png",
                "video_image_width": "1920",
                "video_image_height": "1080",
                "video_image_extension": "png",
                "video_url": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/b2fb1cb7-5316-4a27-b98f-82dc5bd5f292/default.jobtemplate.hls.m3u8",
                "video_previews": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/e84f799c-bf6a-4a51-8148-e2ba63957265/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
                "video_mime_type": "application/x-mpegURL",
                "duration": "0:47",
                "closed_captions": "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/12282e73-635d-489d-ae99-ea39b80e986b.vtt",
                "type": "videos_for_this_product",
            },
            {
                "id": "amzn1.vse.video.00988d17c40e4c1aaf4e968f12f42df2",
                "product_asin": "B000YDDF6O",
                "parent_asin": "B094N3QBWX",
                "related_products": "B00TH0NMUY, B0148NCN9A, B071FK778Y",
                "sponsor_products": "True",
                "title": "VTech Baby Lil' Critters Moosical Beads",
                "public_name": "VTech - Domestic",
                "creator_type": "Vendor",
                "vendor_code": "137GO",
                "vendor_name": "VTech - Domestic",
                "video_image_id": "41l7rF3UDHL",
                "video_image_url": "https://m.media-amazon.com/images/I/41l7rF3UDHL._CR2,0,716,404_SR684,386_.jpg",
                "video_image_url_unchanged": "https://m.media-amazon.com/images/I/41l7rF3UDHL.jpg",
                "video_image_width": "720",
                "video_image_height": "404",
                "video_image_extension": "jpg",
                "video_url": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/v2/242ded54-232e-586e-8f59-f3eeb7a7b799/ShortForm-Generic-480p-16-9-1409173089793-rpcbe5.mp4",
                "video_previews": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/e6d130c8-cb25-419c-9c91-b2e44894f94b/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
                "video_mime_type": "video/mp4",
                "duration": "0:31",
                "type": "videos_for_related_products",
            },
            {
                "id": "amzn1.vse.video.00d6f333c8144ede825b1f0968425ea9",
                "product_asin": "B000YDDF6O",
                "parent_asin": "B094N3QBWX",
                "related_products": "B019ICFYNI",
                "sponsor_products": "True",
                "title": "VTech Baby Rattle and Sing Puppy",
                "public_name": "VTech - Domestic",
                "creator_type": "Vendor",
                "vendor_code": "137GO",
                "vendor_name": "VTech - Domestic",
                "video_image_id": "61iYndC+ZKL",
                "video_image_url": "https://m.media-amazon.com/images/I/61iYndC+ZKL._CR2,0,716,404_SR684,386_.jpg",
                "video_image_url_unchanged": "https://m.media-amazon.com/images/I/61iYndC+ZKL.jpg",
                "video_image_width": "720",
                "video_image_height": "404",
                "video_image_extension": "jpg",
                "video_url": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/v2/78e9aae3-bbd2-5bba-a44e-9a825934775f/ShortForm-Generic-480p-16-9-1409173089793-rpcbe5.mp4",
                "video_previews": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/9de4d1ef-4121-4496-9304-3106aeec9176/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
                "video_mime_type": "video/mp4",
                "duration": "0:41",
                "type": "videos_for_related_products",
            },
            {
                "id": "amzn1.vse.video.07b40c2add7d491fb538bd4062d5ec5e",
                "product_asin": "B000YDDF6O",
                "parent_asin": "B094N3QBWX",
                "related_products": "B07DM86Z43, B079VQYMKC",
                "sponsor_products": "True",
                "title": "Baby Einstein Sea Dreams Soother Review and Demonstration",
                "profile_image_url": "https://images-na.ssl-images-amazon.com/images/S/influencer-profile-image-prod/logo/maddiesdaddie_1611897848921_original._CR0,0,1500,1500_._FMjpg_.png",
                "profile_link": "/shop/maddiesdaddie",
                "public_name": "Maddie's Daddy",
                "creator_type": "Influencer",
                "vendor_code": "maddiesdaddie:shop",
                "vendor_name": "Maddie's Daddy",
                "vendor_tracking_id": "onamzmaddiesd-20",
                "video_image_id": "A1mYQ5ejDVL",
                "video_image_url": "https://m.media-amazon.com/images/I/A1mYQ5ejDVL._CR3,0,1914,1080_SR684,386_.jpg",
                "video_image_url_unchanged": "https://m.media-amazon.com/images/I/A1mYQ5ejDVL.jpg",
                "video_image_width": "1920",
                "video_image_height": "1080",
                "video_image_extension": "jpg",
                "video_url": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/1348accc-6ade-4a92-a492-2adbda82a9c8/default.jobtemplate.hls.m3u8",
                "video_previews": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/edff52fe-b001-45c0-975c-ca1c54de833c/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
                "video_mime_type": "application/x-mpegURL",
                "duration": "3:49",
                "closed_captions": "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/38b620e6-9841-42dc-8dae-25d1b0b7149c.vtt",
                "type": "videos_for_related_products",
            },
            {
                "id": "amzn1.vse.video.0b996eeb78b54505b329ab660498ad7c",
                "product_asin": "B000YDDF6O",
                "parent_asin": "B094N3QBWX",
                "related_products": "B07DM86Z43",
                "sponsor_products": "True",
                "title": "Our Point of View on Baby Einstein Sea Dream Sound Machine",
                "profile_image_url": "https://images-na.ssl-images-amazon.com/images/S/influencer-profile-image-prod/logo/influencer-20a38664_1661823596243_original._CR0,0,1080,1080_._FMjpg_.jpeg",
                "profile_link": "/shop/influencer-20a38664",
                "public_name": "What Tools Inside",
                "creator_type": "Influencer",
                "vendor_code": "influencer-20a38664:shop",
                "vendor_name": "What Tools Inside",
                "vendor_tracking_id": "whattoolsin07-20",
                "video_image_id": "A1p5+CSLWKL",
                "video_image_url": "https://m.media-amazon.com/images/I/A1p5+CSLWKL._CR1,0,1683,950_SR684,386_.png",
                "video_image_url_unchanged": "https://m.media-amazon.com/images/I/A1p5+CSLWKL.png",
                "video_image_width": "1686",
                "video_image_height": "950",
                "video_image_extension": "png",
                "video_url": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/ff6f867b-83ad-4e6d-9bf6-4236e9451fec/default.jobtemplate.hls.m3u8",
                "video_previews": "https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/344e6d40-0902-4ad6-8edb-32ebef54f2e0/videopreview.jobtemplate.mp4.342X192P_20HZ_350KBPS_VER_1_0.mp4,342X192P_20HZ_350KBPS_VER_1_0,video/mp4",
                "video_mime_type": "application/x-mpegURL",
                "duration": "1:44",
                "closed_captions": "en,https://m.media-amazon.com/images/S/vse-vms-closed-captions-artifact-us-east-1-prod/closedCaptions/8fe0d2b3-fcdd-4335-a85e-d0c6a801b2e5.vtt",
                "type": "videos_for_related_products",
            },
        ],
        "is_bundle": False,
        "feature_bullets": [
            "A best selling favorite with thousands of 5 star ratings",
            "Inspires a lifelong love of music.No Assembly Required",
            "Baby can switch between 10 total melodies",
            "Perfectly sized for ages 3 to 36 months",
            "Volume control is music to mom and dad\u2019s ears",
            "Easy to wipe down and clean",
        ],
        "feature_bullets_count": 6,
        "feature_bullets_flat": "Easy to wipe down and clean. Volume control is music to mom and dad\u2019s ears. Perfectly sized for ages 3 to 36 months. Baby can switch between 10 total melodies. Inspires a lifelong love of music.No Assembly Required. A best selling favorite with thousands of 5 star ratings.",
        "important_information": {
            "sections": [
                {
                    "title": "Legal Disclaimer",
                    "body": "Brand New,Guarantee 100% Genuine Product, Satisfaction Guaranteed, Worldwide Shipping Quickly . Buy with Confidence! Thank you for your order.",
                }
            ]
        },
        "top_reviews": [
            {
                "id": "R2DOMAD5SPIZCA",
                "title": "Great toy",
                "body": "I originally bought this when I had my first child. It was one we took everywhere because it distracted and engaged our first baby from infancy. It was super helpful at home and while out...shopping or eating out. I used it with my twins, same use. I have a daughter who is 6 and has cerebral palsy and she STILL loves this toy. It's a cause/reaction toy with wonderful music and lights that still engages her and I'd recommend this for babies as well as developmentally challenged kiddos.Read more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>I originally bought this when I had my first child. It was one we took everywhere because it distracted and engaged our first baby from infancy. It was super helpful at home and while out...shopping or eating out. I used it with my twins, same use. I have a daughter who is 6 and has cerebral palsy and she STILL loves this toy. It\'s a cause/reaction toy with wonderful music and lights that still engages her and I\'d recommend this for babies as well as developmentally challenged kiddos.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "link": "https://www.amazon.com/gp/customer-reviews/R2DOMAD5SPIZCA/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B000YDDF6O",
                "rating": 5,
                "date": {
                    "raw": "Reviewed in the United States on January 19, 2023",
                    "utc": "2023-01-19T00:00:00.000Z",
                },
                "profile": {
                    "name": "jmcc33",
                    "link": "https://www.amazon.com/gp/profile/amzn1.account.AGM5JAMRPDLOXPSUPSBH3CN6WCMA/ref=cm_cr_dp_d_gw_tr?ie=UTF8",
                    "id": "AGM5JAMRPDLOXPSUPSBH3CN6WCMA",
                },
                "vine_program": False,
                "verified_purchase": True,
                "review_country": "us",
                "is_global_review": False,
            },
            {
                "id": "R1MBRFQ2BT25AQ",
                "title": "I don\u2019t do toys with noise",
                "body": "Ever, since I was a child, I knew that when I had children, their toys could not have noise. I am very sensitive to being overstimulated by noise, and I typically think children\u2019s noisy toys are obnoxious. This toy came in a bag of used goods when I had my first child. It ended up being one of his favorite toys and I did not mind it either. I just had my second child five years later, and had to order him one of these as well. It has stopped plenty of fits and aided in many diaper changes. Our first one from six years ago recently turned up and it still works just fine. Good quality fun cute toy. Highly recommend.Read more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>Ever, since I was a child, I knew that when I had children, their toys could not have noise. I am very sensitive to being overstimulated by noise, and I typically think children\u2019s noisy toys are obnoxious.<br>This toy came in a bag of used goods when I had my first child. It ended up being one of his favorite toys and I did not mind it either. I just had my second child five years later, and had to order him one of these as well. It has stopped plenty of fits and aided in many diaper changes. Our first one from six years ago recently turned up and it still works just fine. Good quality fun cute toy. Highly recommend.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "link": "https://www.amazon.com/gp/customer-reviews/R1MBRFQ2BT25AQ/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B000YDDF6O",
                "rating": 5,
                "date": {
                    "raw": "Reviewed in the United States on December 27, 2022",
                    "utc": "2022-12-27T00:00:00.000Z",
                },
                "profile": {
                    "name": "Autumn",
                    "link": "https://www.amazon.com/gp/profile/amzn1.account.AGNNNBBBLYGVRGJ3WO7WKFOFKMVQ/ref=cm_cr_dp_d_gw_tr?ie=UTF8",
                    "id": "AGNNNBBBLYGVRGJ3WO7WKFOFKMVQ",
                },
                "vine_program": False,
                "verified_purchase": True,
                "helpful_votes": 5,
                "review_country": "us",
                "is_global_review": False,
            },
            {
                "id": "R204L2IL9FCOMN",
                "title": "This is my baby\u2019s favorite toy! I would give it more stars if I could!",
                "body": "This is such a spectacular toy for such a low price! I recommend that every parent gets this for their little one! My daughter absolutely loves it! She\u2019s been using it since 3 months. It\u2019s nice because by pressing the center button, it lights up to the beat of the classical music it plays. As you press the button it plays a different song and it cycles through about maybe 7 different songs. There\u2019s a switch at the top that either lets you play it at a lower or higher volume. The pieces on the handle move which also makes it a little more entertaining and great as a teether! I also love this toy because it teaches some coordination as they learn to press the button.Read more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>This is such a spectacular toy for such a low price! I recommend that every parent gets this for their little one! My daughter absolutely loves it! She\u2019s been using it since 3 months. It\u2019s nice because by pressing the center button, it lights up to the beat of the classical music it plays. As you press the button it plays a different song and it cycles through about maybe 7 different songs. There\u2019s a switch at the top that either lets you play it at a lower or higher volume. The pieces on the handle move which also makes it a little more entertaining and great as a teether! I also love this toy because it teaches some coordination as they learn to press the button.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "link": "https://www.amazon.com/gp/customer-reviews/R204L2IL9FCOMN/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B000YDDF6O",
                "rating": 5,
                "date": {
                    "raw": "Reviewed in the United States on December 8, 2022",
                    "utc": "2022-12-08T00:00:00.000Z",
                },
                "profile": {
                    "name": "Tigerlily",
                    "link": "https://www.amazon.com/gp/profile/amzn1.account.AEIO2NOXSGZWPBEFSOFYLV3KPC6Q/ref=cm_cr_dp_d_gw_tr?ie=UTF8",
                    "id": "AEIO2NOXSGZWPBEFSOFYLV3KPC6Q",
                },
                "vine_program": False,
                "verified_purchase": True,
                "helpful_votes": 2,
                "review_country": "us",
                "is_global_review": False,
            },
            {
                "id": "R1CMVPWJ14JVO4",
                "title": "A Favorite",
                "body": "I bought this on a whim when my son was 3 months old, hoping to engage him with developmentally appropriate sensory things. We were so excited when he started figuring out how to push the button on his own, and it has turned into one of his favorite toys by 6 months. It is such a great price, the battery it comes with lasts so long, even if you forget to power it off, and my son gets so much happiness from learning to grip, push to hear the music and see the lights turn on, and he enjoys trying to gum the little beads on top. For such an affordable toy, there are so many benefits to it and offers so much for developmental milestones!Read more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>I bought this on a whim when my son was 3 months old, hoping to engage him with developmentally appropriate sensory things. We were so excited when he started figuring out how to push the button on his own, and it has turned into one of his favorite toys by 6 months. It is such a great price, the battery it comes with lasts so long, even if you forget to power it off, and my son gets so much happiness from learning to grip, push to hear the music and see the lights turn on, and he enjoys trying to gum the little beads on top. For such an affordable toy, there are so many benefits to it and offers so much for developmental milestones!</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "link": "https://www.amazon.com/gp/customer-reviews/R1CMVPWJ14JVO4/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B000YDDF6O",
                "rating": 5,
                "date": {
                    "raw": "Reviewed in the United States on December 5, 2022",
                    "utc": "2022-12-05T00:00:00.000Z",
                },
                "profile": {
                    "name": "Stacey",
                    "link": "https://www.amazon.com/gp/profile/amzn1.account.AFCSD3NS6JE3LAEZ4O3TSOSJ2EVA/ref=cm_cr_dp_d_gw_tr?ie=UTF8",
                    "id": "AFCSD3NS6JE3LAEZ4O3TSOSJ2EVA",
                },
                "vine_program": False,
                "verified_purchase": True,
                "helpful_votes": 2,
                "review_country": "us",
                "is_global_review": False,
            },
            {
                "id": "R14ODRU8ZNDNA9",
                "title": "SHE LOVES THIS!!",
                "body": "I read the reviews and decided to get this for my 10 month old niece. She loves it\u2026.Carrie\u2019s it around and gets down with her bad self to the classic tunes. Inexpensive and well made and I am very happy with this purchase.Read more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>I read the reviews and decided to get this for my 10 month old niece. She loves it\u2026.Carrie\u2019s it around and gets down with her bad self to the classic tunes. Inexpensive and well made and I am very happy with this purchase.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "link": "https://www.amazon.com/gp/customer-reviews/R14ODRU8ZNDNA9/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B000YDDF6O",
                "rating": 5,
                "date": {
                    "raw": "Reviewed in the United States on January 11, 2023",
                    "utc": "2023-01-11T00:00:00.000Z",
                },
                "profile": {
                    "name": "Kathleen",
                    "link": "https://www.amazon.com/gp/profile/amzn1.account.AG7MHQK3CNRHO7QQEK7WKABP44HA/ref=cm_cr_dp_d_gw_tr?ie=UTF8",
                    "id": "AG7MHQK3CNRHO7QQEK7WKABP44HA",
                },
                "vine_program": False,
                "verified_purchase": True,
                "review_country": "us",
                "is_global_review": False,
            },
            {
                "id": "R3NXURHXGPOCJG",
                "title": "This was great!",
                "body": "I got this for my son when he was about 3 months and he loved it! He was almost instantly quiet whenever it was playing , there are two volume settings so it isn\u2019t too loud all the time. We ended up getting one for my niece, and it seems to be doing the same for herRead more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>I got this for my son when he was about 3 months and he loved it! He was almost instantly quiet whenever it was playing , there are two volume settings so it isn\u2019t too loud all the time.<br>We ended up getting one for my niece, and it seems to be doing the same for her</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "link": "https://www.amazon.com/gp/customer-reviews/R3NXURHXGPOCJG/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B000YDDF6O",
                "rating": 5,
                "date": {
                    "raw": "Reviewed in the United States on December 31, 2022",
                    "utc": "2022-12-31T00:00:00.000Z",
                },
                "profile": {
                    "name": "Taylor",
                    "link": "https://www.amazon.com/gp/profile/amzn1.account.AHQQGOQURJ32ZSJUSGVFVJ6T27SA/ref=cm_cr_dp_d_gw_tr?ie=UTF8",
                    "id": "AHQQGOQURJ32ZSJUSGVFVJ6T27SA",
                },
                "vine_program": False,
                "verified_purchase": True,
                "review_country": "us",
                "is_global_review": False,
            },
            {
                "id": "R26WWLVXE5DXRT",
                "title": "Highly Recommend",
                "body": "My almost 5 month old loves this thing!! It\u2019s so simple yet keeps him interested forever. The music is pleasant, unlike some other toys that make me want to go insane after 10 minutes. The colorful beads are fun for them to grab and chew haha. It\u2019s the perfect on-the-go toy!Read more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>My almost 5 month old loves this thing!! It\u2019s so simple yet keeps him interested forever. The music is pleasant, unlike some other toys that make me want to go insane after 10 minutes. The colorful beads are fun for them to grab and chew haha. It\u2019s the perfect on-the-go toy!</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "link": "https://www.amazon.com/gp/customer-reviews/R26WWLVXE5DXRT/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B000YDDF6O",
                "rating": 5,
                "date": {
                    "raw": "Reviewed in the United States on January 2, 2023",
                    "utc": "2023-01-02T00:00:00.000Z",
                },
                "profile": {
                    "name": "KB",
                    "link": "https://www.amazon.com/gp/profile/amzn1.account.AFICP53MDMZ3DQSUI7S2CQGAPY5A/ref=cm_cr_dp_d_gw_tr?ie=UTF8",
                    "id": "AFICP53MDMZ3DQSUI7S2CQGAPY5A",
                },
                "vine_program": False,
                "verified_purchase": True,
                "review_country": "us",
                "is_global_review": False,
            },
            {
                "id": "R3T8G7022PAF6E",
                "title": "Most Loved Toy",
                "body": "This toy is one of my baby's favorites and has been for several months. He doesn't get tired of listening to the music and loves mouthing itRead more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>This toy is one of my baby\'s favorites and has been for several months. He doesn\'t get tired of listening to the music and loves mouthing it</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "link": "https://www.amazon.com/gp/customer-reviews/R3T8G7022PAF6E/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B000YDDF6O",
                "rating": 5,
                "date": {
                    "raw": "Reviewed in the United States on January 15, 2023",
                    "utc": "2023-01-15T00:00:00.000Z",
                },
                "profile": {
                    "name": "Tilly Heintz",
                    "link": "https://www.amazon.com/gp/profile/amzn1.account.AGVD52S4CBDU7OJAAINUFUABASNQ/ref=cm_cr_dp_d_gw_tr?ie=UTF8",
                    "id": "AGVD52S4CBDU7OJAAINUFUABASNQ",
                },
                "vine_program": False,
                "verified_purchase": True,
                "review_country": "us",
                "is_global_review": False,
            },
            {
                "id": "R1ZIF8OCYR8AQF",
                "title": "Brilliant toy!!!",
                "body": "My son absolutely loves this toy. He's 8 months old now and he had it for 2 months now and his face still lights up when he sees it or hears it. The quality of the sound is brilliant (and so rare in a toy) and more importantly the tunes are AMAZING. My husband and I actually press the button ourselves to listen to them, excellent choice and versions. THe lights are very entertaining and go with the music, which is brilliant. My son loves also to chew the little caterpillar head. The handle could be a bit bigger to allow little chunky hands to play with the rotating beads, but not a deal breaker. My son drops it all the time...and still perfectly functioning. Highly recommended if you like good music!Read more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>My son absolutely loves this toy. He\'s 8 months old now and he had it for 2 months now and his face still lights up when he sees it or hears it. The quality of the sound is brilliant (and so rare in a toy) and more importantly the tunes are AMAZING. My husband and I actually press the button ourselves to listen to them, excellent choice and versions. THe lights are very entertaining and go with the music, which is brilliant. My son loves also to chew the little caterpillar head. The handle could be a bit bigger to allow little chunky hands to play with the rotating beads, but not a deal breaker. My son drops it all the time...and still perfectly functioning. Highly recommended if you like good music!</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "rating": 5,
                "date": {
                    "raw": "Reviewed in the United Kingdom on August 8, 2018",
                    "utc": "2018-08-08T00:00:00.000Z",
                },
                "profile": {"name": "Monica"},
                "vine_program": False,
                "verified_purchase": True,
                "helpful_votes": 19,
                "review_country": "gb",
                "is_global_review": True,
            },
            {
                "id": "R17ZAQSW5HP0TM",
                "title": "Almost not annoying! Much loved, but couldn't press the button until 16/17 months.",
                "body": "The least annoying musical baby toy I've encountered. It's almost pleasant. My daughter loves it and always starts dancing as soon as it's on.  We bought it for her first birthday, but she couldn't press the button by herself then, so we didn't use it as much as we thought we would at first. She's nearly 18 months now and has suddenly turned a button-pressing corner and loves it. (I was actually drawn to the big easy button on the design of this, thinking she would find it easier but she actually seemed to master it at exactly the same time as all the other button pressing toys.)  It's our go to toy to take out and about. We have a collection of those plastic loops you get on other random baby toys that we use to attach dummies, toys etc to car seat/ buggy straps/ cot bars to stop things getting dropped, and it's easy to link this on to anything with that using the handle.  Would definitely recommend.Read more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>The least annoying musical baby toy I\'ve encountered. It\'s almost pleasant. My daughter loves it and always starts dancing as soon as it\'s on.<br><br>We bought it for her first birthday, but she couldn\'t press the button by herself then, so we didn\'t use it as much as we thought we would at first. She\'s nearly 18 months now and has suddenly turned a button-pressing corner and loves it. (I was actually drawn to the big easy button on the design of this, thinking she would find it easier but she actually seemed to master it at exactly the same time as all the other button pressing toys.)<br><br>It\'s our go to toy to take out and about. We have a collection of those plastic loops you get on other random baby toys that we use to attach dummies, toys etc to car seat/ buggy straps/ cot bars to stop things getting dropped, and it\'s easy to link this on to anything with that using the handle.<br><br>Would definitely recommend.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "rating": 5,
                "date": {
                    "raw": "Reviewed in the United Kingdom on September 10, 2016",
                    "utc": "2016-09-10T00:00:00.000Z",
                },
                "profile": {"name": "L"},
                "vine_program": False,
                "verified_purchase": True,
                "helpful_votes": 28,
                "review_country": "gb",
                "is_global_review": True,
            },
            {
                "id": "R1LKIC08XS8MMO",
                "title": "'LITTLE-ONES LOVE THIS ITEM'",
                "body": "Must admit, bought this for my Granddaughter for Christmas, she was only born November, so i wasn't really expecting her to have too much interest in it just yet (you know what it's like, new family member, buy a collection of items they'll not use for ages) however, i was wrong, the little one loves both the lights and the tunes that are generated from this relatively small item, she's mesmerised by it. I'd recommend it as an early toy for sure.Read more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>Must admit, bought this for my Granddaughter for Christmas, she was only born November, so i wasn\'t<br>really expecting her to have too much interest in it just yet (you know what it\'s like, new family member,<br>buy a collection of items they\'ll not use for ages) however, i was wrong, the little one loves both the<br>lights and the tunes that are generated from this relatively small item, she\'s mesmerised by it.<br>I\'d recommend it as an early toy for sure.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "rating": 5,
                "date": {
                    "raw": "Reviewed in the United Kingdom on February 7, 2016",
                    "utc": "2016-02-07T00:00:00.000Z",
                },
                "profile": {
                    "name": "rbmusicman/and/movie-fan'",
                    "image": "https://images-eu.ssl-images-amazon.com/images/S/amazon-avatars-global/12d2c049-ce5e-48b0-b86b-138f376db06e._CR62,0,375,375_SX48_.jpg",
                },
                "vine_program": False,
                "verified_purchase": True,
                "helpful_votes": 42,
                "review_country": "gb",
                "is_global_review": True,
            },
            {
                "id": "R3NC3W7J79BBDF",
                "title": "Nice idea but awful cheap quality",
                "body": "I was a bit disappointed when I received the music toy about the quality: even if in original packaging there were darker marks on the white plastic and the rings at the handle have rough bits from production (both see photos). I decided to keep it since the music sounds nice. But after 2 days I noticed black fingerprint like stains on the white plastic which turned out to be the black paint from the edge around the screen which comes off (photo). Absolut NO GO for toys which go into babies mouth!!  Sadly I can not recommend this toy at all.Read more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>I was a bit disappointed when I received the music toy about the quality: even if in original packaging there were darker marks on the white plastic and the rings at the handle have rough bits from production (both see photos). I decided to keep it since the music sounds nice. But after 2 days I noticed black fingerprint like stains on the white plastic which turned out to be the black paint from the edge around the screen which comes off (photo). Absolut NO GO for toys which go into babies mouth!!<br><br>Sadly I can not recommend this toy at all.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "rating": 2,
                "date": {
                    "raw": "Reviewed in the United Kingdom on February 9, 2021",
                    "utc": "2021-02-09T00:00:00.000Z",
                },
                "profile": {"name": "Min"},
                "vine_program": False,
                "verified_purchase": True,
                "review_country": "gb",
                "is_global_review": True,
            },
            {
                "id": "R3P1UK63PEBSWX",
                "title": "After less than 3 months, the product is already  malfunctionning",
                "body": "The toy in itself works as expected. It's not too heavy that a 6-9mo baby has difficulties holding it. When our baby understood that pressing the pad generated a tune, he played with it quite a lot. In that respect it really does the job.  However, there are two major issues: The biggest one is sturdiness: after 2.5 months of use, the toy is already starting to malfunctiong, with the music stuck in looping malfunction sounds instead of the expected melodies. That's definitely a major flaw - I would expect more durability from a reputable company - and the reason for this rating. The other one is the paint wearing off on the pad, which is mentioned in other reviews. It's probably tiny amounts as it wears off over time, but definitely not ideal.Read more",
                "body_html": '<div data-a-expander-name="review_text_read_more" data-a-expander-collapsed-height="300" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" style="max-height:300px"><div data-hook="review-collapsed" aria-expanded="False" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content">             <span>The toy in itself works as expected. It\'s not too heavy that a 6-9mo baby has difficulties holding it. When our baby understood that pressing the pad generated a tune, he played with it quite a lot. In that respect it really does the job.<br><br>However, there are two major issues:<br>The biggest one is sturdiness: after 2.5 months of use, the toy is already starting to malfunctiong, with the music stuck in looping malfunction sounds instead of the expected melodies. That\'s definitely a major flaw - I would expect more durability from a reputable company - and the reason for this rating.<br>The other one is the paint wearing off on the pad, which is mentioned in other reviews. It\'s probably tiny amounts as it wears off over time, but definitely not ideal.</span>   </div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a href="javascript:void(0)" data-csa-c-func-deps="aui-da-a-expander-toggle" data-csa-c-type="widget" data-csa-interaction-events="click" data-hook="expand-collapse-read-more-less" aria-label="Toggle full review text" aria-expanded="False" role="button" data-action="a-expander-toggle" class="a-declarative" data-a-expander-toggle="{&quot;allowLinkDefault&quot;:True, &quot;expand_prompt&quot;:&quot;Read more&quot;, &quot;collapse_prompt&quot;:&quot;Read less&quot;}"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div>',
                "rating": 1,
                "date": {
                    "raw": "Reviewed in the United Kingdom on August 10, 2020",
                    "utc": "2020-08-10T00:00:00.000Z",
                },
                "profile": {"name": "Mochtari de Pierrepont"},
                "vine_program": False,
                "verified_purchase": True,
                "review_country": "gb",
                "is_global_review": True,
            },
        ],
        "buybox_winner": {
            "maximum_order_quantity": {"value": 27, "hard_maximum": True},
            "offer_id": "sHaJBMZN3BH9KDtdtgZRq1L5FJ/q1nMX7kTXJdDivqx+w8+PBDY2BC7QiqCCauwG+ICV0YWQ7YeHJAxclONR0u9iLpo6Rs9YLWqgo8ZAQuO201UkBSfFQ/wNUAyRFJeM6cm9dVp3q/Q=",
            "new_offers_count": 13,
            "new_offers_from": {
                "symbol": "$",
                "value": 9.99,
                "currency": "USD",
                "raw": "$9.99",
            },
            "is_prime": True,
            "is_amazon_fresh": False,
            "condition": {"is_new": True},
            "availability": {
                "type": "in_stock",
                "raw": "In Stock.",
                "dispatch_days": 1,
            },
            "fulfillment": {
                "type": "1p",
                "standard_delivery": {"date": "Thursday, January 26", "name": "FREE"},
                "is_sold_by_amazon": True,
                "amazon_seller": {"name": "Amazon"},
                "is_fulfilled_by_amazon": True,
                "is_fulfilled_by_third_party": False,
                "is_sold_by_third_party": False,
            },
            "price": {"symbol": "$", "value": 9.99, "currency": "USD", "raw": "$9.99"},
            "rrp": {"symbol": "$", "value": 10.49, "currency": "USD", "raw": "$10.49"},
            "shipping": {"raw": "FREE"},
        },
        "more_buying_choices": [
            {
                "price": {
                    "symbol": "$",
                    "value": 15.99,
                    "currency": "USD",
                    "raw": "$15.99",
                },
                "seller_name": "Pristine Shops LLC",
                "seller_link": "https://www.amazon.com/gp/aag/main?ie=UTF8&seller=A3KCW6IWEU807S&isAmazonFulfilled=1&asin=B000YDDF6O&ref_=dp_mbc_seller",
                "free_shipping": True,
                "position": 1,
            }
        ],
        "specifications": [
            {"name": "Product Dimensions", "value": "\u200e5.13 x 5.13 x 1.08 inches"},
            {"name": "Item model number", "value": "\u200e30704"},
            {"name": "Batteries", "value": "\u200e2 AA batteries required."},
            {"name": "Is Discontinued By Manufacturer", "value": "\u200eNo"},
            {"name": "Target gender", "value": "\u200eUnisex"},
            {"name": "Maximum weight recommendation", "value": "\u200e96 Pounds"},
            {"name": "Material Type", "value": "\u200ePolypropylene"},
            {"name": "material_composition", "value": "\u200e100% plastic"},
            {
                "name": "Care instructions",
                "value": "\u200eWipe clean with damp cloth and mild soap. Do not immerse in water.",
            },
            {
                "name": "Additional product features",
                "value": "\u200eMusic, Sound & Lights, Volume Control, Easy to Clean",
            },
            {"name": "Number Of Items", "value": "\u200e1"},
            {"name": "Style", "value": "\u200eTake Along Tunes"},
            {"name": "Batteries required", "value": "\u200eYes"},
            {"name": "Dishwasher safe", "value": "\u200eNo"},
            {"name": "Is portable", "value": "\u200eNo"},
            {"name": "Item Weight", "value": "\u200e3.68 ounces"},
            {"name": "Country/Region of origin", "value": "\u200eChina"},
            {"name": "ASIN", "value": "B000YDDF6O"},
            {
                "name": "Customer Reviews",
                "value": "4.8 out of 5 stars       49,897 ratings          4.8 out of 5 stars",
            },
            {"name": "Best Sellers Rank", "value": "#74 in Toys & Games"},
        ],
        "specifications_flat": "Best Sellers Rank: #74 in Toys & Games. Customer Reviews: 4.8 out of 5 stars       49,897 ratings          4.8 out of 5 stars. ASIN: B000YDDF6O. Country/Region of origin: \u200eChina. Item Weight: \u200e3.68 ounces. Is portable: \u200eNo. Dishwasher safe: \u200eNo. Batteries required: \u200eYes. Style: \u200eTake Along Tunes. Number Of Items: \u200e1. Additional product features: \u200eMusic, Sound & Lights, Volume Control, Easy to Clean. Care instructions: \u200eWipe clean with damp cloth and mild soap. Do not immerse in water. material_composition: \u200e100% plastic. Material Type: \u200ePolypropylene. Maximum weight recommendation: \u200e96 Pounds. Target gender: \u200eUnisex. Is Discontinued By Manufacturer: \u200eNo. Batteries: \u200e2 AA batteries required. Item model number: \u200e30704. Product Dimensions: \u200e5.13 x 5.13 x 1.08 inches.",
        "bestsellers_rank": [
            {
                "category": "Toys & Games",
                "rank": 74,
                "link": "https://www.amazon.com/gp/bestsellers/toys-and-games/ref=pd_zg_ts_toys-and-games",
            },
            {
                "category": "Baby Musical Toys",
                "rank": 1,
                "link": "https://www.amazon.com/gp/bestsellers/toys-and-games/196607011/ref=pd_zg_hrsr_toys-and-games",
            },
            {
                "category": "Preschool Musical Toys",
                "rank": 1,
                "link": "https://www.amazon.com/gp/bestsellers/toys-and-games/251933011/ref=pd_zg_hrsr_toys-and-games",
            },
            {
                "category": "Toddler Music & Sound Toys",
                "rank": 1,
                "link": "https://www.amazon.com/gp/bestsellers/toys-and-games/251970011/ref=pd_zg_hrsr_toys-and-games",
            },
        ],
        "material": "\u200e100% plastic",
        "weight": "\u200e3.68 ounces",
        "dimensions": "\u200e5.13 x 5.13 x 1.08 inches",
        "model_number": "\u200e30704",
        "bestsellers_rank_flat": "Category: Toys & Games | Rank: 74, Category: Baby Musical Toys | Rank: 1, Category: Preschool Musical Toys | Rank: 1, Category: Toddler Music & Sound Toys | Rank: 1",
    },
    "brand_store": {
        "id": "E1E1E35C-3C06-4F59-A626-D50E3F999C85",
        "link": "https://www.amazon.com/stores/BabyEinstein/page/E1E1E35C-3C06-4F59-A626-D50E3F999C85",
    },
    "frequently_bought_together": {
        "total_price": {
            "symbol": "$",
            "value": 22.37,
            "currency": "USD",
            "raw": "$22.37",
        },
        "products": [
            {
                "asin": "B000YDDF6O",
                "title": "Baby Einstein Glow & Discover Light Bar Activity Station, 1 Count (Pack of 1)",
                "link": "https://www.amazon.com/dp/B000YDDF6O",
                "image": "https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif",
                "price": {
                    "symbol": "$",
                    "value": 9.99,
                    "currency": "USD",
                    "raw": "$9.99",
                },
            },
            {
                "asin": "B008J1QP7Y",
                "title": "Bright Starts Oball Shaker Rattle Toy, Ages Newborn +",
                "link": "https://www.amazon.com/dp/B008J1QP7Y",
                "image": "https://images-na.ssl-images-amazon.com/images/I/61vCn24QwwL._AC_UL116_SR116,116_.jpg",
                "price": {
                    "symbol": "$",
                    "value": 2.39,
                    "currency": "USD",
                    "raw": "$2.39",
                },
            },
            {
                "asin": "B08NQ169XF",
                "title": "Smily Mia Penguin Buddy Never Drop Silicone Baby Teething Toy for 0-6month Infants, Baby Chew Toys for Sucking Needs, Hand Pa",
                "link": "https://www.amazon.com/dp/B08NQ169XF",
                "image": "https://images-na.ssl-images-amazon.com/images/I/61qpBdL+AnL._AC_UL116_SR116,116_.jpg",
                "price": {
                    "symbol": "$",
                    "value": 9.99,
                    "currency": "USD",
                    "raw": "$9.99",
                },
            },
        ],
    },
    "compare_with_similar": [
        {
            "asin": "B000YDDF6O",
            "image": "https://m.media-amazon.com/images/I/81s+p-98uyL._AC_SS450_.jpg",
            "title": "Baby Einstein Take Along Tunes Musical Toy, Ages 3 months +",
            "rating": 5,
            "ratings_total": 49897,
            "price": {"symbol": "$", "value": 9.99, "currency": "USD", "raw": "$9.99"},
            "link": "https://www.amazon.com/dp/B000YDDF6O",
        },
        {
            "asin": "B06Y1192MF",
            "image": "https://m.media-amazon.com/images/I/81BY6UK+PlL._AC_SS450_.jpg",
            "title": "Baby Einstein Glow & Discover Light Bar Activity Station, 1 Count (Pack of 1)",
            "rating": 4.5,
            "ratings_total": 16920,
            "price": {
                "symbol": "$",
                "value": 14.99,
                "currency": "USD",
                "raw": "$14.99",
            },
            "link": "https://www.amazon.com/dp/B06Y1192MF",
        },
        {
            "asin": "B00TFAOIY0",
            "image": "https://m.media-amazon.com/images/I/81aoCA1HvHL._AC_SS450_.jpg",
            "title": "Baby Einstein Star Bright Symphony Plush Musical Take-Along Toy, Ages Newborn + (Pack of 1)",
            "rating": 4.5,
            "ratings_total": 13673,
            "price": {
                "symbol": "$",
                "value": 11.47,
                "currency": "USD",
                "raw": "$11.47",
            },
            "link": "https://www.amazon.com/dp/B00TFAOIY0",
        },
        {
            "asin": "B0148NCN9A",
            "image": "https://m.media-amazon.com/images/I/71ZzKSXSrJL._AC_SS450_.jpg",
            "title": "VTech Baby Lil' Critters Moosical Beads Amazon Exclusive, Purple Small",
            "rating": 5,
            "ratings_total": 21786,
            "price": {
                "symbol": "$",
                "value": 14.32,
                "currency": "USD",
                "raw": "$14.32",
            },
            "link": "https://www.amazon.com/dp/B0148NCN9A",
        },
        {
            "asin": "B008J1QP7Y",
            "image": "https://m.media-amazon.com/images/I/61vCn24QwwL._AC_SS450_.jpg",
            "title": "Bright Starts Oball Shaker Rattle Toy, Ages Newborn +",
            "rating": 4.5,
            "ratings_total": 57032,
            "price": {"symbol": "$", "value": 2.39, "currency": "USD", "raw": "$2.39"},
            "link": "https://www.amazon.com/dp/B008J1QP7Y",
        },
        {
            "asin": "B004AHMCMI",
            "image": "https://m.media-amazon.com/images/I/71wRUjmaujL._AC_SS450_.jpg",
            "title": "Sassy Developmental Bumpy Ball | Easy to Grasp Bumps Help Develop Motor Skills | for Ages 6 Months and Up | Colors May Vary",
            "rating": 4.5,
            "ratings_total": 30292,
            "price": {
                "symbol": "$",
                "value": 11.08,
                "currency": "USD",
                "raw": "$11.08",
            },
            "link": "https://www.amazon.com/dp/B004AHMCMI",
        },
    ],
}
