name: main

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: lgeiger/black-action@master
        with:
          args: ". --check"

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the image
        run: docker compose -f "docker-compose.yml" up -d --build

      - name: Run the tests
        run: docker compose exec django coverage run --source='.' manage.py test

      - name: Update Coverage Badge
        uses: we-cli/coverage-badge-action@main

      - name: Clean up
        if: always()
        run: docker-compose -f "docker-compose.yml" down
